TRUNCATE TABLE city  CASCADE;
TRUNCATE TABLE country CASCADE;
TRUNCATE TABLE customer CASCADE;
TRUNCATE TABLE hotel CASCADE;
TRUNCATE TABLE hotel_feature CASCADE;
TRUNCATE TABLE  hotel_feature_association CASCADE;
TRUNCATE TABLE  hotel_feature_type CASCADE;
TRUNCATE TABLE  hotel_photo CASCADE;
TRUNCATE TABLE  location CASCADE;
TRUNCATE TABLE room CASCADE;
TRUNCATE TABLE room_feature CASCADE;
TRUNCATE TABLE room_feature_association CASCADE;
TRUNCATE TABLE room_feature_type CASCADE;
TRUNCATE TABLE room_type CASCADE;
TRUNCATE TABLE room_type_photo CASCADE;





